# Generated by Django 3.0.2 on 2020-12-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('dateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('oneYearContract', models.BooleanField(default=False)),
                ('collegeContract', models.BooleanField(default=False)),
                ('masterContract', models.BooleanField(default=False)),
                ('graduateCollege', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='teacher/images/')),
            ],
        ),
    ]
