# Generated by Django 3.0.2 on 2020-12-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(choices=[('1', 'ODA School 01'), ('2', 'ODA School 02'), ('3', 'ODA School 03'), ('4', 'ODA School 04'), ('5', 'ODA School 05'), ('6', 'ODA School 06'), ('7', 'ODA School 07'), ('8', 'ODA School Center')], max_length=1)),
                ('image', models.ImageField(upload_to='school/images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
