# Generated by Django 3.0.2 on 2020-12-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
    ]
