# Generated by Django 3.0.2 on 2020-12-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201210_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Classes')),
                ('teacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
    ]
