# Generated by Django 3.0.2 on 2020-12-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_teaching_schoolname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameInKhmer', models.CharField(max_length=250)),
                ('nameInEnglish', models.CharField(max_length=250)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('dateOfBirth', models.DateField()),
                ('enrollDate', models.DateField()),
                ('phoneNumber', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('familySituation', models.CharField(choices=[('1', 'Poor'), ('2', 'Midle'), ('3', 'Rich')], max_length=1)),
                ('graduted', models.BooleanField(default=False)),
                ('uniformProject', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='student/images/')),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Classes')),
                ('schoolName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SchoolName')),
                ('teacherName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Teacher')),
            ],
        ),
    ]
