# Generated by Django 3.0.2 on 2020-12-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201211_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finishWithODA',
            field=models.DateField(blank=True, null=True),
        ),
    ]
