# Generated by Django 3.0.2 on 2020-12-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201211_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studyComputer',
            field=models.BooleanField(default=False),
        ),
    ]
